# Makefile
CXX = g++
CXXFLAGS = -std=c++17 -Iinclude -Isrc
SRC = \
    main.cpp \
	src/domain/letter.cpp \
	src/service/letter_service.cpp \
    src/app.cpp \
	src/crypto.cpp \
	src/utils.cpp
OBJ = $(SRC:.cpp=.o)
TARGET = build

all: $(TARGET)

$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) $(SRC) -o $(TARGET)

clean:
	del /Q *.o $(TARGET) 2>nul || rm -f *.o $(TARGET)
